### PR TITLE
Updated dependencies and added dependabot.yaml

### PR DESCRIPTION
**Pull request by austindimmer**
I updated dependencies and validated a cdk deploy into AWS SSM from my local machine that worked properly after the updates. 

I am not able to deploy when pushed to GitHub since I observe the build error 

Error: EACCES: permission denied, copyfile '/github/workspace/lambda/code.zip' -> '/github/workspace/test/cdk.out/asset.b315f2666ffba45b9546f766eb2c8b91074230ccaa4de54bb117845b6dc97d15.zip'

I tried to debug the build error a little but it escapes me why this is failing.

### CODE REVIEW

**Comment by austindimmer** [comment]
My project code is based on CDK 1.77.0 so I needed to update this lib. I am having some issues with getting this to build when code is pushed to github. The build fails with error EACCES: permission denied. It runs locally and deploys and deletes in AWS as expected. I am currently running the code by checking out my forked repo with the CDK 1.77.0 update applied and referencing it as a git submodule. I will see how well this works out as a temporary solution.

**Comment by udondan** [comment]
Hey Austin,

thanks for your effort here, I see this gave you quite some joy. :)

Let me understand your setup first.

You're using CDK with TypeScript or another language?

You said you're using CDK 1.77.0. But the changes refer to 1.79.0. I assume you've upgrade your app in the meantime?

I don't think there exists any solution at all to solve dependencies from 3rd party packages in a good way. In the `package.json` I'm using caret versions. Basically that means, _install the latest_. And that works, as long as you're as well using the latest CDK version in your app. If you use any older version, it's gonna fail.

To my knowledge - and that might be not enough - there is no way to tell a package to just use any version that is already available through a dependency in another package or from a direct dependency in the `package.json`.

I tried many things already:

- exclude `package-lock.json` from publishing
- remove direct deps, only use peer deps
- instead of using caret versions, use `1.x`

It's all the same. You always end up with the very latest version when installing.

The logical thing to do, would be to just remove all dependencies and tell the developer to take care of referencing the correct version in the `package.json` of the app. But this won't work because jsii won't compile with this setup. It requires at very least peer-dependencies.

Other L3 construct developers publish a new CDK package for every new version of the CDK itself which includes an exact dependency to that version. Yeah, that works. And I hate that "solution". It means if you change functionality of this package, you need to release a new version for every supported CDK version. Or only support the very latest CDK version. And that... is pretty much exactly what is supported with the ^caret version reference.

Let me cycle back, to the problem you were facing and what I _think_ what's going on. You said the package didn't work with version 1.77.0. I assume at the time you were installing the package, there already was a newer release. So when you ran `npm i cdk-ssm-document` you actually installed cdk dependencies with version  1.78.0 or 1.79.0. And that's why it failed. You then made some changes to your app and now you're using 1.79.0.

The changes you did to the `package.json` basically update the version from `^1.47.0` to `^1.79.0`. I'm quite confident in saying this wouldn't work anymore, because yesterday they released 1.80.0. And both version definitions just say, _install the latest_. Before that release and after you had updated you app to 1.79.0 I assume my original package would have actually worked for you.

Only an exact version like 1.79.0 would solve the problem, but only for those using CDK version 1.79.0.

Now here's is how I use this package in our production apps. (btw one of them is running CDK 1.77.0) When you install it, you have to use the latest CDK version in your app. So today the latest version is 1.80.0. If your app runs 1.80.0, you're good. If it runs any older version, you'll get a version conflict. If they release 1.81.0 tomorrow, an `npm i cdk-ssm-document` again would install the latest version and it will conflict.

Therefore in our apps `package.json` we also use the _latest_ CDK versions, and if we wanted to update to a newer version of this package, we would in fact need to delete the `node_modules` and `package-lock.json` to ensure we also install the very latest CDK package versions. Yeah, not cool at all. But it guarantees you are able to use this package with any version of the CDK, as long as you're using the latest CDK version at the time of installing. If you don't wnat to upgrade the CDK version, you cannot upgrade this packages version.

Hope that makes sense :)

Cheers,
Daniel

---

I assume, one could write a little tool to fix these version conflicts. After installing the package, this tool could inspect the `package-lock.json`/`yarn.lock` and update all versions of the nested dependencies with the exact version found at the top level for the cdk core package. Then wipe the `node_modules` and install the deps again. This then should install compatible versions. I'll try to look into this when I find some time.

**Comment by austindimmer** [comment]
Hi Daniel,

Yes thanks indeed for your thoughtful comments. Also thanks so much for sharing your lib. It is very useful. I was hoping that I could do a quick upgrade and contribute back but in the end it turned out to be a little more complicated than I had anticipated.

I did in fact get my fork working yesterday in the end I ran with 1.80.0. For a while I ran into the dreaded CDK version hell TypeScript wall of compilation errors! I’ve seen this a few times on my CDK Adventures. I solved it by deleting node_modules and package lock and removing a class that referenced a different L3 construct. The other construct had a hard dependency on a different version of the CDK. If I want to continue to use it I will have to fork that repo as well and make it reference the version of the CDK I am building against. 

I prefer the strategy of not using the ^ versioning and specify exactly that version I need. This seems to provide me with the stability I need for a few months and then I upgrade CDK version when I need to. That’s just been my preference.

I’m also using dependabot on my projects to try and keep up with updates and Security patches etc. My idea was to introduce it to this repo in the hope that it might make dependency updates etc a little less burdensome in future.

Today in my fork I had some energy to try and get past the deploy error and I got it to work. I added in a step to the test workflow file that set some build permissions. You should see that in my fork.

I am also using the modern CDK bootstrapping method on my projects. “New Style Stack Synthesis” so there are some differences in my bootstrapping infra over what I think you are testing against. This change can be rolled back.

i will be happy to reopen this Pull request if you think it might be worth it. I’m interested to see if my changes will deploy with your test workflow.

Have a Merry Christmas!

**Comment by udondan** [comment]
Hi Austin!

Merry Christmas to you too! 🎅🏼 

I think I have finally figured this out. I have created another PR via #12 which seems to solve this for all CDK versions. The solution seems to be to list the CDK dependencies both as `peerDependencies` and `devDependencies`, not as `dependencies`.

With this config, you can use the package with any CDK version. I have tested this with 1.70.0 and 1.80.0, both with NodeJS and Python. All seem to be happy.

You have to add the required peer dependencies to your apps `package.json`. The required peer dependencies have also been added to the readme (in the [deps](https://github.com/udondan/cdk-ssm-document/tree/deps) branch).

The tricky part was, that this setup will not work in the test dir with the relative import. When using relative imports, npm for some reason, will install the latest CDK ^packages and not those listed in `test/package.json`. So all my tests with older CDK versions failed. That's why I thought peer-deps are not working. Tough it's working perfectly fine when installing a package from npmjs.

Another complication was, that this package depends on another package of mine: [cdk-iam-floyd](https://www.npmjs.com/package/cdk-iam-floyd). And there of course I also had to adjust the deps/peer-deps before it possibly could work.

I haven't merged the #12 yet for two reasons:

- Maybe you want to give the [deps](https://github.com/udondan/cdk-ssm-document/tree/deps) branch a spin?
- I feel you should get some credit in the history of the project for all the time you have spent. At very least for figuring out the permission issues (don't know what GitHub changed there to break that) Thanks for that! If you like you can send another PR with only this and the docker tag updates before I merge #12.

The dependabot thingy should be obsolete with the new dependency setup. The only direct dependency is cdk-iam-floyd which again has no direct dependencies.

Cheers,
Daniel

**Comment by austindimmer** [comment]
Hi Daniel,

Very nicely done. I appreciate your efforts. I intend to return on 4th Jan and I will be happy to take this for a spin. I will also be happy to create a pull request. Of course if you just want to crack on and get it done that will be fine by me.

**Comment by udondan** [comment]
No hurry here. Take your time and and enjoy the time off! 😸

**Comment by austindimmer** [comment]
Hi Daniel,

Sorry for the delay in getting to this. I have been snowed under since we started back. The fork that I made of this repo solved the immediate problem. I will be working again on some SSM stuff probably in the next two weeks. When I get there I will take out this new version for a test drive. In the meantime. Please feel free to merge, no need to wait on me if you are happy with the code.

**Comment by udondan** [comment]
Hey Austin, same here, hadn't have time until now. I merged #12 now, it's released as v1.3.2. Thanks again! :)

**Pull request closed without merging**
